#!/bin/bash
# Generate backend/.env from infra/.env for production deployment
# Usage: ./generate-env.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Source the infra .env
if [ ! -f "$SCRIPT_DIR/.env" ]; then
    echo "ERROR: $SCRIPT_DIR/.env not found. Copy .env.example to .env and fill in values."
    exit 1
fi
source "$SCRIPT_DIR/.env"

# Generate secrets if not set
SECRET_KEY="${SECRET_KEY:-$(openssl rand -hex 32)}"
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -hex 16)}"
REDIS_PASSWORD="${REDIS_PASSWORD:-$(openssl rand -hex 16)}"

# Write back generated passwords to infra/.env if they were auto-generated
if ! grep -q "^DB_PASSWORD=." "$SCRIPT_DIR/.env" 2>/dev/null; then
    echo "DB_PASSWORD=${DB_PASSWORD}" >> "$SCRIPT_DIR/.env"
fi
if ! grep -q "^REDIS_PASSWORD=." "$SCRIPT_DIR/.env" 2>/dev/null; then
    echo "REDIS_PASSWORD=${REDIS_PASSWORD}" >> "$SCRIPT_DIR/.env"
fi

cat > "$ROOT_DIR/backend/.env" << EOF
# Auto-generated by infra/generate-env.sh — do not edit directly
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

DEBUG=false
ENVIRONMENT=production

SECRET_KEY=${SECRET_KEY}

DATABASE_URL=postgresql+asyncpg://csgateway:${DB_PASSWORD}@postgres:5432/csgateway
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

CORS_ORIGINS=["https://${DOMAIN:-localhost}"]

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
GOOGLE_API_KEY=${GOOGLE_API_KEY:-}

GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID:-}
EOF

chmod 600 "$ROOT_DIR/backend/.env"
echo "Generated backend/.env for domain: ${DOMAIN:-localhost}"
echo "Database password: ${DB_PASSWORD:0:4}..."
echo "Redis password: ${REDIS_PASSWORD:0:4}..."
